service:
  port: 8001

api:
  base_path: '/api/v1'

tf_serving:
  #for running without docker
  host: '0.0.0.0'
#  host: '172.17.0.2' for running in docker
  port: 9000

model:
  name: 'detector'
  signature_name: 'serving_default'
